//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestriPhotoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisito
    {
        public Requisito()
        {
            this.Condicao = new HashSet<Condicao>();
        }
    
        public long id { get; set; }
        public string local { get; set; }
        public string localizacao { get; set; }
        public long idUtilizador { get; set; }
        public Nullable<int> idPorto { get; set; }
    
        public virtual ICollection<Condicao> Condicao { get; set; }
        public virtual Porto Porto { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
